import axios from 'axios';
import type { NextPage } from 'next';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import axiosInstance, { removeAuthToken, setAuthToken } from '../src/api/axiosInstance';
import styles from '../styles/Home.module.css';
import { CustomSession } from '../src/types/Session';

const Authorize: NextPage = () => {
    const { data: session, status } = useSession({
        required: true,
        // onUnauthenticated: () => {
        //     console.log('removing token');
        //     removeAuthToken();
        // },
    });
    // const session = data as CustomSession;
    // console.log('status', status);
    // console.log('data', data);

    // useEffect(() => {
    //     if (status == 'authenticated' && session?.accessToken) {
    //         console.log('setting aut token: ', session.accessToken);
    //         setAuthToken(session.accessToken as string);
    //     }
    // }, [status, session?.accessToken]);

    const [password, setPassword] = useState('');
    const router = useRouter();

    const onSignIn = async () => {
        const item: UserLogins = {
            username: 'admin',
            password: 'admin',
        };

        try {
            let result = await axiosInstance.post('/authorize', item);
            let accessToken = result.data.token;
            console.log('setToken', accessToken);
            setAuthToken(accessToken);
            console.log('aaa');
            const listResult = await axiosInstance.get('/authorize');
            console.log(listResult.data);
        } catch {
            console.log('error');
        }
    };

    const onGoogleAuth = async () => {
        //let result = await axiosInstance.get('/users/google-auth');
        //router.push('/api/backend/users/google-auth?redirectUri=' + window.location.pathname + window.location.search);
        // router.push(
        //     'http://localhost:5249/api/users/google-auth?redirectUri=' +
        //         window.location.pathname +
        //         window.location.search
        // );
        signIn();
    };

    const onCheck = async () => {
        //axiosInstance.defaults.headers.post['Access-Control-Allow-Origin'] = '*';
        axiosInstance
            .get('/users/me', { withCredentials: true })
            .then((v) => console.log('ok'))
            .catch((e) => console.log(e));
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h2 className={styles.title}>You need to authorize</h2>
                <label>Login</label>
                <input type="text"></input>
                <label>Password</label>
                <input type="password" onInput={(v) => console.log(v)}></input>
                <button onClick={onSignIn}>Go</button>
                <button onClick={onGoogleAuth}>Via googl</button>
                <button onClick={onCheck}>check</button>
            </main>
        </div>
    );
};

export default Authorize;

interface UserLogins {
    username: string;
    password: string;
}
