// <auto-generated />
using System;
using System.Collections.Generic;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220510050952_UpdatePhase")]
    partial class UpdatePhase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.CardEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("BackSideText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<List<string>>("Examples")
                        .HasMaxLength(255)
                        .HasColumnType("text[]");

                    b.Property<string>("FrontSideText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ParentUserId", "ParentCollectionId", "Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DB.Models.CardRepeatQueueEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentCardId")
                        .HasColumnType("smallint");

                    b.Property<long>("ParentRepeatsScheduleUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("PhaseIndex")
                        .HasColumnType("smallint");

                    b.HasKey("ParentUserId", "ParentCollectionId", "ParentCardId", "ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId", "Id");

                    b.HasIndex("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId");

                    b.ToTable("Queue");
                });

            modelBuilder.Entity("DB.Models.CollectionEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CardsCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefaultBackSide")
                        .HasColumnType("boolean");

                    b.Property<short>("ThemeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ParentUserId", "Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("DB.Models.PhaseEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefaultValueSide")
                        .HasColumnType("boolean");

                    b.Property<long>("SecondsFromLastPhase")
                        .HasColumnType("bigint");

                    b.HasKey("ParentUserId", "ParentRepeatsScheduleId", "Id");

                    b.ToTable("SchedulePhases");
                });

            modelBuilder.Entity("DB.Models.PhaseRememberEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentPhaseId")
                        .HasColumnType("smallint");

                    b.Property<long>("RepeatedUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ParentUserId", "ParentRepeatsScheduleId", "ParentPhaseId", "RepeatedUserId", "Id");

                    b.HasIndex("RepeatedUserId");

                    b.ToTable("PhaseRememberEntities");
                });

            modelBuilder.Entity("DB.Models.RefreshTokenEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParentUserId", "Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DB.Models.RememberEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentCardId")
                        .HasColumnType("smallint");

                    b.Property<long>("ParentRepeatsScheduleUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("PhaseIndex")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("RepeatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ParentUserId", "ParentCollectionId", "ParentCardId", "ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId", "PhaseIndex", "Id");

                    b.HasIndex("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId");

                    b.ToTable("RememberWeights");
                });

            modelBuilder.Entity("DB.Models.RepeatsScheduleEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CardsCountPerPhase")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ForgottenBehavior")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ParentUserId", "Id");

                    b.ToTable("RepeatsSchedules");
                });

            modelBuilder.Entity("DB.Models.ThemeEntity", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("DB.Models.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DB.Models.UserMetadataEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("FinishedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("FinishedCollections")
                        .HasColumnType("smallint");

                    b.Property<short>("NotStartedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("NotStartedCollections")
                        .HasColumnType("smallint");

                    b.Property<short>("StartedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("StartedCollections")
                        .HasColumnType("smallint");

                    b.HasKey("ParentUserId");

                    b.ToTable("UserMetadata");
                });

            modelBuilder.Entity("DB.Models.UserPasswordsEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("ParentUserId");

                    b.ToTable("UsersPasswords");
                });

            modelBuilder.Entity("DB.Models.CardEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.CollectionEntity", "ParentCollection")
                        .WithMany("Cards")
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.CardRepeatQueueEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.RepeatsScheduleEntity", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.CollectionEntity", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.CardEntity", "ParentCard")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId", "ParentCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCard");

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.CollectionEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany("Collections")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.ThemeEntity", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("DB.Models.PhaseEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.RepeatsScheduleEntity", "ParentRepeatsSchedule")
                        .WithMany("Phases")
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.PhaseRememberEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.UserEntity", "RepeatedUser")
                        .WithMany()
                        .HasForeignKey("RepeatedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.RepeatsScheduleEntity", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.PhaseEntity", "ParentPhase")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId", "ParentPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentPhase");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");

                    b.Navigation("RepeatedUser");
                });

            modelBuilder.Entity("DB.Models.RefreshTokenEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.RememberEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.RepeatsScheduleEntity", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.CollectionEntity", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Models.CardEntity", "ParentCard")
                        .WithMany("Remembers")
                        .HasForeignKey("ParentUserId", "ParentCollectionId", "ParentCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCard");

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.RepeatsScheduleEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.UserMetadataEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithOne()
                        .HasForeignKey("DB.Models.UserMetadataEntity", "ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.UserPasswordsEntity", b =>
                {
                    b.HasOne("DB.Models.UserEntity", "ParentUser")
                        .WithOne("PasswordHash")
                        .HasForeignKey("DB.Models.UserPasswordsEntity", "ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("DB.Models.CardEntity", b =>
                {
                    b.Navigation("Remembers");
                });

            modelBuilder.Entity("DB.Models.CollectionEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("DB.Models.RepeatsScheduleEntity", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("DB.Models.UserEntity", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("PasswordHash");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
