// <auto-generated />
using System;
using System.Collections.Generic;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231231050002_AddCommentToRemembers")]
    partial class AddCommentToRemembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("user_id_sequence");

            modelBuilder.Entity("Domain.Card.Card", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<List<string>>("Examples")
                        .HasMaxLength(255)
                        .HasColumnType("text[]");

                    b.Property<string>("MeaningText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PromptText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RememberingText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ParentUserId", "ParentCollectionId", "Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Domain.Collection.Collection", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CardsCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefaultBackSide")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<short>("ThemeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ParentUserId", "Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Domain.Deprecated.DbModels.CollectionPublicationEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<long>("DislikesCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LikesCount")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<long>("SubscribersCount")
                        .HasColumnType("bigint");

                    b.HasKey("ParentUserId", "ParentCollectionId");

                    b.ToTable("CollectionPublications");
                });

            modelBuilder.Entity("Domain.Deprecated.DbModels.PublicCollectionSubscriber", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<long>("SubscriberUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.HasKey("ParentUserId", "ParentCollectionId", "SubscriberUserId");

                    b.HasIndex("SubscriberUserId");

                    b.ToTable("PublicCollectionSubscriber");
                });

            modelBuilder.Entity("Domain.Dictionary.Translation.WordTranslation", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("WordId", "LanguageId", "Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Translations", (string)null);
                });

            modelBuilder.Entity("Domain.Dictionary.Word.LanguageWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Word");

                    b.ToTable("Words", (string)null);
                });

            modelBuilder.Entity("Domain.Language.Language", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NativeLanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TranslationLink")
                        .HasColumnType("text");

                    b.Property<string>("TranslationLinkTitle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "English",
                            NativeLanguageName = "English"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Russian",
                            NativeLanguageName = "Русский"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Japanese",
                            NativeLanguageName = "日本語"
                        });
                });

            modelBuilder.Entity("Domain.Queue.CardRepeatQueue", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentCardId")
                        .HasColumnType("smallint");

                    b.Property<long>("ParentRepeatsScheduleUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("PhaseIndex")
                        .HasColumnType("smallint");

                    b.HasKey("ParentUserId", "ParentCollectionId", "ParentCardId", "ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId", "Id");

                    b.HasIndex("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId");

                    b.ToTable("Queue", (string)null);
                });

            modelBuilder.Entity("Domain.RelearningCard.RelearningCard", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<short>("CollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("CardId")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "CollectionId", "CardId");

                    b.ToTable("RelearningCards", (string)null);
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Phase.Entities.PhaseRememberEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentPhaseId")
                        .HasColumnType("smallint");

                    b.Property<long>("RepeatedUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ParentUserId", "ParentRepeatsScheduleId", "ParentPhaseId", "RepeatedUserId", "Id");

                    b.HasIndex("RepeatedUserId");

                    b.ToTable("PhaseRememberEntities");
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Phase.Phase", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDefaultValueSide")
                        .HasColumnType("boolean");

                    b.Property<string>("OnLearnDescription")
                        .HasColumnType("text");

                    b.Property<long>("SecondsFromLastPhase")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ParentUserId", "ParentRepeatsScheduleId", "Id");

                    b.ToTable("SchedulePhases", (string)null);
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Remember.Remember", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentCollectionId")
                        .HasColumnType("smallint");

                    b.Property<short>("ParentCardId")
                        .HasColumnType("smallint");

                    b.Property<long>("ParentRepeatsScheduleUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("ParentRepeatsScheduleId")
                        .HasColumnType("smallint");

                    b.Property<short>("PhaseIndex")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("RepeatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ParentUserId", "ParentCollectionId", "ParentCardId", "ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId", "PhaseIndex", "Id");

                    b.HasIndex("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId");

                    b.ToTable("RememberWeights", (string)null);
                });

            modelBuilder.Entity("Domain.Schedule.RepeatsSchedule", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CardsCountPerPhase")
                        .HasColumnType("smallint");

                    b.Property<string>("DefaultPhaseDescription")
                        .HasColumnType("text");

                    b.Property<string>("DefaultPhaseShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefaultRepeatPhaseDescription")
                        .HasColumnType("text");

                    b.Property<string>("DefaultRepeatPhaseShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ForgottenBehavior")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean");

                    b.Property<string>("OnStartLearningDescription")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ParentUserId", "Id");

                    b.ToTable("RepeatsSchedules", (string)null);
                });

            modelBuilder.Entity("Domain.Theme.Theme", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short?>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Domain.User.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParentUserId", "Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.User.Entities.UserMetadata", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("FinishedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("FinishedCollections")
                        .HasColumnType("smallint");

                    b.Property<short>("NotStartedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("NotStartedCollections")
                        .HasColumnType("smallint");

                    b.Property<short>("StartedCards")
                        .HasColumnType("smallint");

                    b.Property<short>("StartedCollections")
                        .HasColumnType("smallint");

                    b.Property<short>("SuggestTranslationLanguageId")
                        .HasColumnType("smallint");

                    b.HasKey("ParentUserId");

                    b.HasIndex("SuggestTranslationLanguageId");

                    b.ToTable("UserMetadata");
                });

            modelBuilder.Entity("Domain.User.Entities.UserPassword", b =>
                {
                    b.Property<long>("ParentUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("ParentUserId");

                    b.ToTable("UsersPasswords", (string)null);
                });

            modelBuilder.Entity("Domain.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('user_id_sequence')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"), "user_id_sequence");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Card.Card", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Collection.Collection", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Collection.Collection", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Theme.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Domain.Deprecated.DbModels.CollectionPublicationEntity", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Collection.Collection", "ParentCollection")
                        .WithOne("CollectionPublicationEntity")
                        .HasForeignKey("Domain.Deprecated.DbModels.CollectionPublicationEntity", "ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Deprecated.DbModels.PublicCollectionSubscriber", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User.User", "SubscriberUser")
                        .WithMany()
                        .HasForeignKey("SubscriberUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Collection.Collection", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Deprecated.DbModels.CollectionPublicationEntity", "CollectionPublication")
                        .WithMany("Subscribers")
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionPublication");

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentUser");

                    b.Navigation("SubscriberUser");
                });

            modelBuilder.Entity("Domain.Dictionary.Translation.WordTranslation", b =>
                {
                    b.HasOne("Domain.Language.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Dictionary.Word.LanguageWord", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Domain.Dictionary.Word.LanguageWord", b =>
                {
                    b.HasOne("Domain.Language.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Queue.CardRepeatQueue", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Schedule.RepeatsSchedule", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Collection.Collection", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Card.Card", "ParentCard")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId", "ParentCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCard");

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Phase.Entities.PhaseRememberEntity", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User.User", "RepeatedUser")
                        .WithMany()
                        .HasForeignKey("RepeatedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Schedule.RepeatsSchedule", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Schedule.Entities.Phase.Phase", "ParentPhase")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId", "ParentPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentPhase");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");

                    b.Navigation("RepeatedUser");
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Phase.Phase", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Schedule.RepeatsSchedule", "ParentRepeatsSchedule")
                        .WithMany("Phases")
                        .HasForeignKey("ParentUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Schedule.Entities.Remember.Remember", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Schedule.RepeatsSchedule", "ParentRepeatsSchedule")
                        .WithMany()
                        .HasForeignKey("ParentRepeatsScheduleUserId", "ParentRepeatsScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Collection.Collection", "ParentCollection")
                        .WithMany()
                        .HasForeignKey("ParentUserId", "ParentCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Card.Card", "ParentCard")
                        .WithMany("Remembers")
                        .HasForeignKey("ParentUserId", "ParentCollectionId", "ParentCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCard");

                    b.Navigation("ParentCollection");

                    b.Navigation("ParentRepeatsSchedule");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Schedule.RepeatsSchedule", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.Theme.Theme", b =>
                {
                    b.HasOne("Domain.Language.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.User.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.User.Entities.UserMetadata", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithOne("Metadata")
                        .HasForeignKey("Domain.User.Entities.UserMetadata", "ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Language.Language", "SuggestTranslationLanguage")
                        .WithMany()
                        .HasForeignKey("SuggestTranslationLanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");

                    b.Navigation("SuggestTranslationLanguage");
                });

            modelBuilder.Entity("Domain.User.Entities.UserPassword", b =>
                {
                    b.HasOne("Domain.User.User", "ParentUser")
                        .WithOne("PasswordHash")
                        .HasForeignKey("Domain.User.Entities.UserPassword", "ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Domain.User.User", b =>
                {
                    b.OwnsOne("Domain.User.ValueObjects.UserName", "UserName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Card.Card", b =>
                {
                    b.Navigation("Remembers");
                });

            modelBuilder.Entity("Domain.Collection.Collection", b =>
                {
                    b.Navigation("CollectionPublicationEntity");
                });

            modelBuilder.Entity("Domain.Deprecated.DbModels.CollectionPublicationEntity", b =>
                {
                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("Domain.Schedule.RepeatsSchedule", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Domain.User.User", b =>
                {
                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PasswordHash");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
