version: '3.4'

services:
  backend:
    image: cr.yandex/crphggso9r6t8kclldqf/intervallearningapi:test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports: #USE EXPOSE
      - "5249:80"
      - "7249:443"
      #- "7249:7249"
      #- "5249:5249"

  client:
    image: cr.yandex/crphggso9r6t8kclldqf/client:test
    ports:
      - "3000:3000"

  proxy:
    depends_on:
      - backend
      - client
    image: cr.yandex/crphggso9r6t8kclldqf/nginx:test
    ports:
      - "443:443"
      - "80:80"

