version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: IntervalLearningApi/Dockerfile
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  client:
    build:
      context: ../interval-learning-web
      dockerfile: Dockerfile

  proxy:
    build:
      context: ../nginx
      dockerfile: Dockerfile
