<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
    <RootNamespace>GlobalTools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.15.2" />
  </ItemGroup>

</Project>
